QLBH_AnkerShop/Areas/Admin/Controllers/DonHangController.cs
using DATA;
using QLBH_AnkerShop.App_Start;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLBH_AnkerShop.Areas.Admin.Controllers
{
    public class DonHangController : Controller
    {
		// GET: Admin/DonHang
		[RoleAdmin]
		public ActionResult DanhSach(string selected)
        {
			mapDonHang map = new mapDonHang();
			var ds = map.DanhSach();
			ViewBag.Selected = selected;
			if (!string.IsNullOrEmpty(selected))
			{
				
				ds = ds.Where(x => x.TrangThai == selected).ToList();
				ViewBag.count = ds.Count;
				return View(ds);

			}
			return View(ds);
        }

	

		[RoleAdmin]
		public ActionResult ChiTietDonHang(string id)
        {
            mapDonHang map = new mapDonHang();
            
            return View(map.GetChiTiet(id));
        }

		[RoleAdmin]
		public ActionResult XoaDonHang()
		{
			return View();
		}

		[RoleAdmin]
		[HttpPost]
		public ActionResult XoaDonHang(string id)
		{
			mapDonHang map = new mapDonHang();
			map.XoaDonHang(id);
			return RedirectToAction("Danhsach","donhang");
		}

		[RoleAdmin]
		public ActionResult XacNhanGiao(string id)
		{
			mapDonHang map =new mapDonHang();
			map.SetTrangThaiDonHang(id);
			return Redirect("/admin/DonHang/danhsach");
		}
	}
}

QLBH_AnkerShop/Controllers/DonHangController.cs
using DATA;
using DATA.Entity;
using QLBH_AnkerShop.App_Start;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace QLBH_AnkerShop.Controllers
{
    public class DonHangController : Controller
    {
		// GET: DonHang
		KhachHang user = SessionConfig.GetUser();
		[RoleUser]
		public ActionResult Index()
        {
			mapDonHang map = new mapDonHang();
			return View(map.DanhSach().Where(m => m.IdKH == user.Id).ToList());
		}

		// GET: DonHang/Details/5
		public ActionResult Details(string id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			mapDonHang map = new mapDonHang();
			var dh = map.GetChiTiet(id);
			if (dh == null)
			{
				return HttpNotFound();
			}
			return View(dh);
		}
	}
}

QLBH_AnkerShop/Areas/Admin/Views/DonHang/ChiTietDonHang.cshtml
@model DATA.Entity.DonHang

@{
    ViewBag.Title = "Anker | Đơn Hàng #" + @Model.Id;
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="w-full h-screen overflow-x-hidden border-t flex flex-col">
    <div class="py-14 px-4 md:px-6 2xl:px-20 2xl:container 2xl:mx-auto">
        <div class="flex justify-start item-start space-y-2 flex-col">
            <h1 class="text-3xl dark:text-white lg:text-4xl font-semibold leading-7 lg:leading-9 text-gray-800">Order #@Model.Id</h1>
            <p class="text-base dark:text-gray-300 font-medium leading-6 text-gray-600">@Model.NgayTaoDon</p>
        </div>
        <div class="mt-10 flex flex-col xl:flex-row jusitfy-center items-stretch w-full xl:space-x-8 space-y-4 md:space-y-6 xl:space-y-0">
            <div class="flex flex-col justify-start items-start w-full space-y-4 md:space-y-6 xl:space-y-8">
                <div class="flex flex-col justify-start items-start dark:bg-gray-800 bg-gray-50 px-4 py-4 md:py-6 md:p-6 xl:p-8 w-full">
                    <p class="text-lg md:text-xl dark:text-white font-semibold leading-6 xl:leading-5 text-gray-800">Giỏ Hàng Của Khách Hàng</p>
                    @{
                        DATA.mapDonHang map = new DATA.mapDonHang();
                        var ds = map.GetSanPhamDonHangs(Model.Id);

                    }
                    @foreach (var item in ds)
                    {
                        <div class="mt-4 md:mt-6 flex flex-col md:flex-row justify-start items-start md:items-center md:space-x-6 xl:space-x-8 w-full">
                            <div class="pb-4 md:pb-8 w-full md:w-40">
                                @{
                                    var imageUrl = item.Anh;
                                    if (!System.IO.File.Exists(Server.MapPath(imageUrl)))
                                    {
                                        imageUrl = Url.Content("/assets/imgs/index/product/pro_1.webp");
                                    }
                                }
                                <img class="w-full hidden md:block" src="@imageUrl"
                                     alt="Product" />
                                <img class="w-full md:hidden" src="@imageUrl"
                                     alt="Product" />
                            </div>
                            <div class="border-b border-gray-200 md:flex-row flex-col flex justify-between items-start w-full pb-8 space-y-4 md:space-y-0">
                                <div class="w-full flex flex-col justify-start items-start space-y-8">
                                    <h3 class="text-xl dark:text-white xl:text-2xl font-semibold leading-6 text-gray-800">@item.TenSP</h3>
                                    <div class="flex justify-start items-start flex-col space-y-2">
                                        <p class="text-sm dark:text-white leading-none text-gray-800"><span class="dark:text-gray-400 text-gray-300">Màu: </span> Đen</p>
                                        <p class="text-sm dark:text-white leading-none text-gray-800"><span class="dark:text-gray-400 text-gray-300">Loại: </span> Nhỏ</p>
                                        <p class="text-sm dark:text-white leading-none text-gray-800"><span class="dark:text-gray-400 text-gray-300">Danh Mục: </span> @item.DanhMuc</p>
                                    </div>
                                </div>
                                <div class="flex justify-between space-x-8 items-start w-full">
                                    <p class="text-base dark:text-white xl:text-lg leading-6">@string.Format("{0:#,0}", item.Gia)đ</p>
                                    <p class="text-base dark:text-white xl:text-lg leading-6 text-gray-800">x @item.SoLuong</p>
                                    <p class="text-base dark:text-white xl:text-lg font-semibold leading-6 text-gray-800">@string.Format("{0:#,0}", item.Gia)đ</p>
                                </div>
                            </div>
                        </div>
                    }
                </div>
                <div class="flex justify-center flex-col md:flex-row flex-col items-stretch w-full space-y-4 md:space-y-0 md:space-x-6 xl:space-x-8">
                    <div class="flex flex-col px-4 py-6 md:p-6 xl:p-8 w-full bg-gray-50 dark:bg-gray-800 space-y-6">
                        <h3 class="text-xl dark:text-white font-semibold leading-5 text-gray-800">Sơ Lược</h3>
                        <div class="flex justify-center items-center w-full space-y-4 flex-col border-gray-200 border-b pb-4">
                            <div class="flex justify-between w-full">
                                <p class="text-base dark:text-white leading-4 text-gray-800">Tổng tạm tính</p>
                                <p class="text-base dark:text-gray-300 leading-4 text-gray-600">@(string.Format("{0:#,0}", (Model.TongTienThanhToan - Model.PhuongThuc.PhiVanChuyen)))đ</p>
                            </div>
                            <div class="flex justify-between items-center w-full">
                                <p class="text-base dark:text-white leading-4 text-gray-800">Giảm giá</p>
                                <p class="text-base dark:text-gray-300 leading-4 text-gray-600">0đ (0%)</p>
                            </div>
                            <div class="flex justify-between items-center w-full">
                                <p class="text-base dark:text-white leading-4 text-gray-800">Phí vận chuyển</p>
                                <p class="text-base dark:text-gray-300 leading-4 text-gray-600">@(string.Format("{0:#,0}", Model.PhuongThuc.PhiVanChuyen))đ</p>
                            </div>
                        </div>
                        <div class="flex justify-between items-center w-full">
                            <p class="text-base dark:text-white font-semibold leading-4 text-gray-800">Tổng</p>
                            <p class="text-base dark:text-gray-300 font-semibold leading-4 text-gray-600">@(string.Format("{0:#,0}", Model.TongTienThanhToan))đ</p>
                        </div>
                    </div>
                    <div class="flex flex-col justify-center px-4 py-6 md:p-6 xl:p-8 w-full bg-gray-50 dark:bg-gray-800 space-y-6">
                        <h3 class="text-xl dark:text-white font-semibold leading-5 text-gray-800">@(Model.TrangThai == "Ðã giao"? "Vận Chuyển Thành Công" : "Đang Vận Chuyển")</h3>
                        <div class="flex justify-between items-start w-full">
                            <div class="flex justify-center items-center space-x-4">
                                <div class="w-8 h-8">
                                    <img class="w-full h-full" alt="logo" src="https://i.ibb.co/L8KSdNQ/image-3.png" />
                                </div>
                                <div class="flex flex-col justify-start items-center">
                                    <p class="text-lg leading-6 dark:text-white font-semibold text-gray-800">@Model.PhuongThuc.TenPT<br /><span class="font-normal">Giao hàng trong 72h</span></p>
                                </div>
                            </div>
                            <p class="text-lg font-semibold leading-6 dark:text-white text-gray-800">@(string.Format("{0:#,0}", Model.PhuongThuc.PhiVanChuyen))đ</p>
                        </div>
                        <div class="w-full flex justify-center items-center">
                            <button class="hover:bg-black dark:bg-white dark:text-gray-800 dark:hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-800 py-5 w-96 md:w-full bg-gray-800 text-base font-medium leading-4 text-white">Theo Dõi Đơn Hàng</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="bg-gray-50 dark:bg-gray-800 w-full xl:w-96 flex justify-between items-center md:items-start px-4 py-6 md:p-6 xl:p-8 flex-col">
                <h3 class="text-xl dark:text-white font-semibold leading-5 text-gray-800">Khách Hàng</h3>
                <div class="flex flex-col md:flex-row xl:flex-col justify-start items-stretch h-full w-full md:space-x-6 lg:space-x-8 xl:space-x-0">
                    <div class="flex flex-col justify-start items-start flex-shrink-0">
                        <div class="flex justify-center w-full md:justify-start items-center space-x-4 py-8 border-b border-gray-200">
                            <img src="https://static-00.iconduck.com/assets.00/avatar-default-symbolic-icon-2048x1949-pq9uiebg.png" class="w-[56px] h-[56px] object-cover" width="56" height="56" alt="avatar" />
                            <div class="flex justify-start items-start flex-col space-y-2">
                                <p class="text-base dark:text-white font-semibold leading-4 text-left text-gray-800">@Model.KhachHang.Ten</p>
                                <p class="text-sm dark:text-gray-300 leading-5 text-gray-600">#@Model.KhachHang.Id</p>
                            </div>
                        </div>

                        <div class="flex justify-center text-gray-800 dark:text-white md:justify-start items-center space-x-4 py-4 border-b border-gray-200 w-full">
                            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M19 5H5C3.89543 5 3 5.89543 3 7V17C3 18.1046 3.89543 19 5 19H19C20.1046 19 21 18.1046 21 17V7C21 5.89543 20.1046 5 19 5Z" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" />
                                <path d="M3 7L12 13L21 7" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" />
                            </svg>
                            <p class="cursor-pointer text-sm leading-5 ">@Model.KhachHang.TaiKhoan</p>
                        </div>
                    </div>
                    <div class="flex justify-between xl:h-full items-stretch w-full flex-col mt-6 md:mt-0">
                        <div class="flex justify-center md:justify-start xl:flex-col flex-col md:space-x-6 lg:space-x-8 xl:space-x-0 space-y-4 xl:space-y-12 md:space-y-0 md:flex-row items-center md:items-start">
                            <div class="flex justify-center md:justify-start items-center md:items-start flex-col space-y-4 my-2">
                                <p class="text-base dark:text-white font-semibold leading-4 text-center md:text-left text-gray-800">Điện Thoại</p>
                                <p class="w-48 lg:w-full dark:text-gray-300 xl:w-48 text-center md:text-left text-sm leading-5 text-gray-600">@Model.DienThoai</p>
                            </div>
                            <div class="flex justify-center md:justify-start items-center md:items-start flex-col space-y-4 xl:mt-8">
                                <p class="text-base dark:text-white font-semibold leading-4 text-center md:text-left text-gray-800">Địa Chỉ Giao Hàng</p>
                                <p class="w-48 lg:w-full dark:text-gray-300 xl:w-48 text-center md:text-left text-sm leading-5 text-gray-600">@Model.DiaChi</p>
                            </div>

                            <div class="flex justify-center md:justify-start items-center md:items-start flex-col space-y-4 xl:mt-8">
                                <p class="text-base dark:text-white font-semibold leading-4 text-center md:text-left text-gray-800">Ghi Chú Đơn Hàng</p>
                                <p class="w-48 lg:w-full dark:text-gray-300 xl:w-48 text-center md:text-left text-sm leading-5 text-gray-600">@Model.GhiChuDonHang</p>
                            </div>
                        </div>
                        <div class="flex w-full justify-center items-center md:justify-start md:items-start">
                            <a href="/admin/donhang/danhsach" class="mt-6 md:mt-0 dark:border-white dark:hover:bg-gray-900 dark:bg-transparent dark:text-white py-5 hover:bg-gray-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-800 border border-gray-800 font-medium w-96 2xl:w-full text-base font-medium leading-4 text-gray-800 text-center">Danh Sách Đơn Hàng</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

QLBH_AnkerShop/Areas/Admin/Views/DonHang/DanhSach.cshtml
@model IEnumerable<DATA.Entity.DonHang>

@{
    ViewBag.Title = "Anker | Đơn Hàng";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<p tabindex="0" class="focus:outline-none text-base sm:text-lg md:text-xl lg:text-2xl font-bold leading-normal text-gray-800 m-2">Danh Sách Đơn Hàng</p>

<div class="w-full h-screen overflow-x-hidden border-t flex flex-col">
    <div class="sm:px-6 w-full">
        <div class="px-4 md:px-10 py-4 md:py-7">
            <div class="flex items-center justify-between">
                <p tabindex="0" class="focus:outline-none text-base sm:text-lg md:text-xl lg:text-2xl font-bold leading-normal text-gray-800 m-2 "></p>

                <div class="py-3 px-4 flex items-center text-sm font-medium leading-none text-gray-600 bg-gray-200 hover:bg-gray-300 cursor-pointer rounded">
                    <p>Sắp xếp</p>
                    <select aria-label="select" class="focus:text-indigo-600 focus:outline-none bg-transparent ml-1">
                        <option class="text-sm text-indigo-800"></option>
                        <option class="text-sm text-indigo-800">Ngày cũ nhất</option>
                        <option class="text-sm text-indigo-800">Ngày mới nhất</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="bg-white py-4 md:py-7 px-4 md:px-8 xl:px-10">
            <div class="sm:flex items-center justify-between">
                <div class="flex items-center">
                    <a class="rounded-full focus:outline-none focus:ring-2  focus:bg-indigo-50 focus:ring-indigo-800" href="/admin/DonHang/danhsach">
                        <div class="py-2 px-8  rounded-full @(ViewBag.selected == null? "bg-indigo-100 text-indigo-700" : "text-gray-600" )">
                            <p>Tất cả</p>
                        </div>
                    </a>
                    <a class="rounded-full focus:outline-none focus:ring-2 focus:bg-indigo-50 focus:ring-indigo-800 ml-4 sm:ml-8" href="/admin/DonHang/danhsach?selected=Ðang+giao">
                        <div class="py-2 px-8 hover:text-indigo-700 hover:bg-indigo-100 rounded-full @(ViewBag.selected == "Ðang giao"? " bg-indigo-100 text-indigo-700" : "text-gray-600" )">
                            <p>Đang giao</p>
                        </div>
                    </a>
                    <a class="rounded-full focus:outline-none focus:ring-2 focus:bg-indigo-50 focus:ring-indigo-800 ml-4 sm:ml-8" href="/admin/DonHang/danhsach?selected=Ðã+giao">
                        <div class="py-2 px-8 hover:text-indigo-700 hover:bg-indigo-100 rounded-full @(ViewBag.selected == "Ðã giao" ? " bg-indigo-100 text-indigo-700" : "text-gray-600" )">
                            <p>Đã giao</p>
                        </div>
                    </a>
                </div>
                <button onclick="popuphandler(true)" class="focus:ring-2 focus:ring-offset-2 focus:ring-indigo-600 mt-4 sm:mt-0 inline-flex items-start justify-start px-6 py-3 bg-indigo-700 hover:bg-indigo-600 focus:outline-none rounded">
                    <p class="text-sm font-medium leading-none text-white">Add Task</p>
                </button>
            </div>
            <div class="mt-7 overflow-x-auto">
                <table class="w-full whitespace-nowrap">
                    <tbody>
                        @foreach (var item in Model)
                        {
                        
                        <tr tabindex="0" class="focus:outline-none h-16 border border-gray-100 rounded">
                            <td class="">
                                <div class="flex items-center pl-5">
                                    <p class="text-base font-medium leading-none text-gray-700 mr-2">#@item.Id</p>

                                </div>
                            </td>

                            <td class="pl-12">
                                <div class="flex items-center">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20" fill="none">
                                        <path d="M9.16667 2.5L16.6667 10C17.0911 10.4745 17.0911 11.1922 16.6667 11.6667L11.6667 16.6667C11.1922 17.0911 10.4745 17.0911 10 16.6667L2.5 9.16667V5.83333C2.5 3.99238 3.99238 2.5 5.83333 2.5H9.16667" stroke="#52525B" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round"></path>
                                        <circle cx="7.50004" cy="7.49967" r="1.66667" stroke="#52525B" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round"></circle>
                                    </svg>
                                    <p class="text-sm leading-none text-gray-600 ml-2">@item.TrangThai</p>
                                </div>
                            </td>

                            <td class="pl-10">
                                <div class="flex items-center">
                                    <p class="text-sm leading-none text-gray-600 ml-2">@item.PhuongThuc.TenPT</p>
                                </div>
                            </td>

                            <td class="">
                                <div class="flex items-center pl-5">
                                    <p class="text-base font-medium leading-none text-gray-700 mr-2"> @string.Format("{0:#,0}", item.TongTienThanhToan)đ</p>

                                </div>
                            </td>
                            
                            <td class="pl-5">
                                <button class="py-3 px-3 text-sm focus:outline-none leading-none text-red-700 bg-red-100 rounded"> @item.NgayTaoDon.Value.ToString("dd/MM/yyyy HH:mm")</button>
                            </td>

                            <td class="pl-4">
                                <a href="@Url.Action("XacNhanGiao","DonHang", new { id = item.Id })" class="focus:ring-2  @(item.TrangThai == "Ðang giao" ? "" : "pointer-events-none") focus:ring-offset-2 focus:ring-red-300 text-sm leading-none text-gray-600 py-3 px-5 bg-gray-100 rounded hover:bg-gray-200 focus:outline-none" type="button" onclick="toggleModal('modal-id')">
                                    @(item.TrangThai == "Ðang giao" ? "Xác nhận đã giao" : "Giao thành công")
                                </a>
                            </td>

                            <td class="pl-4">
                                <a href="@Url.Action("xoadonhang","donhang", new { id = item.Id })" class="focus:ring-2 focus:ring-offset-2 focus:ring-red-300 text-sm leading-none text-gray-600 py-3 px-5 bg-gray-100 rounded hover:bg-gray-200 focus:outline-none">Xóa</a>
                            </td>
                            <td class="pl-4">
                                <a href="@Url.Action("chitietdonhang","donhang", new { id = item.Id })" class="focus:ring-2 focus:ring-offset-2 focus:ring-red-300 text-sm leading-none text-gray-600 py-3 px-5 bg-gray-100 rounded hover:bg-gray-200 focus:outline-none" type="button" onclick="toggleModal('modal-id')">
                                    Chi Tiết
                                </a>
                            </td>

                        </tr>
                    }
                        </tbody>
                    </table>
            </div>
        </div>
    </div>
</div>


<style>
    .checkbox:checked + .check-icon {
        display: flex;
    }
</style>
<script>
    function dropdownFunction(element) {
        var dropdowns = document.getElementsByClassName("dropdown-content");
        var i;
        let list = element.parentElement.parentElement.getElementsByClassName("dropdown-content")[0];
        list.classList.add("target");
        for (i = 0; i < dropdowns.length; i++) {
            if (!dropdowns[i].classList.contains("target")) {
                dropdowns[i].classList.add("hidden");
            }
        }
        list.classList.toggle("hidden");
    }</script>

QLBH_AnkerShop/Areas/Admin/Views/DonHang/XoaDonHang.cshtml
@model DATA.Entity.DonHang

@{
    ViewBag.Title = "Anker | Xóa Đơn Hàng";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

    <div>
        <main class="antialiased bg-gray-200 text-gray-900 font-sans overflow-x-hidden">
            <div class="relative px-4 min-h-screen md:flex md:items-center md:justify-center">
                <div class="bg-black opacity-25 w-full h-full absolute z-10 inset-0"></div>
                <div class="bg-white rounded-lg md:max-w-md md:mx-auto p-4 fixed inset-x-0 bottom-0 z-50 mb-4 mx-4 md:relative">
                    <div class="md:flex items-center">
                        @*<div class="rounded-full border border-gray-300 flex items-center justify-center w-16 h-16 flex-shrink-0 mx-auto">
                                <i class="bx bx-error text-3xl"></i>
                            </div>*@
                        <div class="mt-4 md:mt-0 md:ml-6 text-center md:text-left">
                            <p class="font-bold">Bạn có muốn xóa đơn hàng này ?</p>
                            <p class="text-sm text-gray-700 mt-1">
                                Bạn sẽ mất tất cả dữ liệu về đơn hàng này. Hành động này không thể được hoàn tác.
                            </p>
                        </div>
                    </div>
                    <div class="text-center md:text-right mt-4 md:flex md:justify-end gap-2">
                        <button class="block w-full md:inline-block md:w-auto px-4 py-3 md:py-2 bg-gray-200 rounded-lg font-semibold text-sm mt-4 md:mt-0 md:order-1">
                            @Html.ActionLink("Hủy bỏ", "danhsach", "donhang")
                        </button>
                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-actions no-color">
                                <input type="submit" value="Xóa" class=" cursor-pointer block w-full md:inline-block md:w-auto px-4 py-3 md:py-2 bg-red-200 text-red-700 rounded-lg font-semibold text-sm md:ml-2 md:order-2" />
                            </div>
                        }

                    </div>
                </div>
            </div>
        </main>
    </div>